### ISSUE TITLE
How to solve？

### ISSUE THREAD

**Issue by Dreams-ComeTrue** [GabrielDornelles/TorchNN-OCR#1]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/123959882/215493044-1b46b167-7930-4402-a213-d0e4bd4d7b43.png">

**And：Could you please prepare a novice guide for me. I joined GitHub this month, perhaps because of my own interest. I want to study this project. Thank you very much!**

**Comment by GabrielDornelles** [comment]
Hi @Dreams-ComeTrue , thank you for your interest in the project!

I just wrote a Wiki with this guide: https://github.com/GabrielDornelles/pytorch-ocr/wiki

To what I see, your error message looks like you haven't done the Data Setup as the project expects. It's explained in the above link, let me know if you have more questions.

**Comment by Dreams-ComeTrue** [comment]
_Reply_
> Hi @Dreams-ComeTrue , thank you for your interest in the project!
> 
> I just wrote a Wiki with this guide: https://github.com/GabrielDornelles/pytorch-ocr/wiki
> 
> To what I see, your error message looks like you haven't done the Data Setup as the project expects. It's explained in the above link, let me know if you have more questions.

Hi@GabrielDornelles ，thank you for your reply！
I'm sorry, but I haven't solved the problem after reading your wiki. I want trouble you to  solve my questions.Very sorry！
<img width="1081" alt="question" src="https://user-images.githubusercontent.com/123959882/215947975-54c5e580-9dea-45bf-9413-65f5b9f68ea2.png">
**Thank you very much for your help,**

_Sir, your help is of great significance to me and is the driving force for me to learn pytorch-ocr. It is my honor to truly understand the project you wrote. Although it is not worth mentioning in your opinion, it is an opportunity for me to gain interesting knowledge!Thank you again!_

**Comment by Dreams-ComeTrue** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/123959882/215963254-141b9be0-bc9d-41aa-acf8-5ff7e1e7dc02.png">

**Comment by Dreams-ComeTrue** [comment]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/123959882/215963459-2295978e-1f7c-48a7-bc6a-50a63639f2d9.png">
_**Where is the output directory of the file?**_

**Comment by Dreams-ComeTrue** [comment]
_replenish_
**<img width="482" alt="image" src="https://user-images.githubusercontent.com/123959882/215968888-e692c1bd-a83d-46ba-9de3-75951996d309.png">**（_config.yaml_，two false）

**Comment by Dreams-ComeTrue** [comment]
_replenish_
![GV4SvMEd](https://user-images.githubusercontent.com/123959882/215969354-80760bfe-1bcb-45aa-86e9-6af278fb2ec6.png)

**Comment by Dreams-ComeTrue** [comment]
<img width="228" alt="image" src="https://user-images.githubusercontent.com/123959882/215970862-0e9508b0-0ac6-4a76-a168-60361e604a90.png">

_All directories_（**Excuse me is it true？**）

**Comment by Dreams-ComeTrue** [comment]
Another question is why my **SAVE_ CHECKPOINTS** is false？（_In config.yaml_）

**Comment by Dreams-ComeTrue** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/123959882/215973929-4435385f-f9d4-487b-9027-305b591ec227.png">

**Comment by GabrielDornelles** [comment]
I see that your images are PNG file, try to change this line: https://github.com/GabrielDornelles/pytorch-ocr/blob/main/train.py#L49

change it from **jpg** to **png**.

---

The **SAVE_ CHECKPOINTS** are by default False because it saves the model every epoch, and the model is about 50mb, so if you train for 100 epoches, you'll have 5gb of checkpoints, and that will scale with the number of trainings you do, but if you do want to save the checkpoints you can just set it to True.

**Comment by Dreams-ComeTrue** [comment]
> I see that your images are PNG file, try to change this line: https://github.com/GabrielDornelles/pytorch-ocr/blob/main/train.py#L49
> 
> change it from **jpg** to **png**.
> 
> The **SAVE_ CHECKPOINTS** are by default False because it saves the model every epoch, and the model is about 50mb, so if you train for 100 epoches, you'll have 5gb of checkpoints, and that will scale with the number of trainings you do, but if you do want to save the checkpoints you can just set it to True.

_Thank you. New message appears when rewriting again_
<img width="498" alt="image" src="https://user-images.githubusercontent.com/123959882/216209143-8493e388-ef63-44a3-871f-b3e63ec69917.png">

**Comment by GabrielDornelles** [comment]
Looks like either you don't have a GPU or you didn't install CUDA drivers, by default the model is set to train on gpu, but you can change it on processing.device, which is set to **cuda**, put **cpu**. If you have a NVIDIA GPU, make sure to install the Cuda drivers

**Comment by Dreams-ComeTrue** [comment]
![Uploading image.png…]()

**Comment by Dreams-ComeTrue** [comment]
> Looks like either you don't have a GPU or you didn't install CUDA drivers, by default the model is set to train on gpu, but you can change it on processing.device, which is set to **cuda**, put **cpu**. If you have a NVIDIA GPU, make sure to install the Cuda drivers

Sorry, could you be more specific?

**Comment by Dreams-ComeTrue** [comment]
<img width="241" alt="question" src="https://user-images.githubusercontent.com/123959882/216526215-029694f9-738d-476f-84c2-3d258386d2c1.png">

**Comment by Dreams-ComeTrue** [comment]
I didn't use anaconda, I just installed pytorch.

**Comment by Dreams-ComeTrue** [comment]
I didn't use anaconda, I just installed pystore。

**Comment by GabrielDornelles** [comment]
You dont have pytorch + GPU support (as you can see in +cpu). To train with GPU you need to install pytorch + cuda support.

Take a look here: https://pytorch.org/get-started/locally/
